version: "3"

vars:
  CICD_TAG: "0.0.11"

tasks:
  copy-to-build:
    cmds:
      - scp Dockerfile green-machine.ts:/home/kube/repos/polite-cicd
      - scp Taskfile.yaml green-machine.ts:/home/kube/repos/polite-cicd
      - scp -r scripts/ green-machine.ts:/home/kube/repos/polite-cicd
    silent: false

  docker-build:
    cmds:
      - docker build --no-cache -t polite-cicd:dev .
    silent: false

  # push:
  #   cmds:
  #     - docker build -t politeauthority/polite-cicd:{{.CICD_TAG}} .
  #     - echo "Completed build politeauthority/polite-cicd:{{.CICD_TAG}}"
  #   silent: false

  get-version:
    cmds:
      - cat VERSION
    silent: true

  dev-run:
    cmds:
      - docker run --name="polite-cicd" -d politeauthority/polite-cicd:{{.CICD_TAG}} tail -f /dev/null
    silent: false

  dev-exec:
    cmds:
      - docker exec -it polite-cicd bash
    silent: false
