version: "3"

vars:
  CICD_TAG: "0.0.9"

tasks:
  build:
    cmds:
      - docker build -t politeauthority/polite-cicd:{{.CICD_TAG}} .
      - echo "Completed build politeauthority/polite-cicd:{{.CICD_TAG}}"
    silent: false

  # push:
  #   cmds:
  #     - docker build -t politeauthority/polite-cicd:{{.CICD_TAG}} .
  #     - echo "Completed build politeauthority/polite-cicd:{{.CICD_TAG}}"
  #   silent: false


  get-version:
    cmds:
      - cat VERSION
    silent: true

  dev-run:
    cmds:
      - docker run --name="polite-cicd" -d politeauthority/polite-cicd:{{.CICD_TAG}} tail -f /dev/null
    silent: false

  dev-exec:
    cmds:
      - docker exec -it polite-cicd bash
    silent: false
