version: '3'

vars:
<<<<<<< 0.0.9
  CICD_TAG: "0.0.9"
=======
  CICD_TAG: "0.0.2"
>>>>>>> main

tasks:
  build:
    cmds:
      - docker build -t politeauthority/polite-cicd:{{.CICD_TAG}} .
      - echo "Completed build politeauthority/polite-cicd:{{.CICD_TAG}}"
    silent: false
<<<<<<< 0.0.9

  # push:
  #   cmds:
  #     - docker build -t politeauthority/polite-cicd:{{.CICD_TAG}} .
  #     - echo "Completed build politeauthority/polite-cicd:{{.CICD_TAG}}"
  #   silent: false

  run-docker:
    cmds: -|
        docker run polite-cicd \
          --name=polite-cicd \
          politeauthority/polite-cicd:{{.CICD_TAG}}
    silent: false

=======
>>>>>>> main
  get-version:
    cmds:
      - cat VERSION
    silent: true
<<<<<<< 0.0.9

=======
>>>>>>> main
  dev-run:
    cmds: 
      - docker run --name="polite-cicd" -d politeauthority/polite-cicd:{{.CICD_TAG}} tail -f /dev/null
    silent: false

  dev-exec:
    cmds: 
      - docker exec -it polite-cicd bash
    silent: false
