# Create Production
# Builds and stores a new version of the image, reading the value of the `VERSION` file for the tag
# name

name: Create Production

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: self-hosted
    container:
      # image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      image: politeauthority/polite-cicd:latest
      credentials:
        username: ${{ vars.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: harbor.squid-ink.us
          username: ${{ vars.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Container
        run: |
          echo "Run Task: Build"
          task docker-build

      - name: Push Container - Harbor
        run: |
          REPO="harbor.squid-ink.us"
          IMAGE_NAME="politeauthority/polite-cicd"
          IMAGE_ID=$(docker images --format "{{.ID}}" --sort=created | head -n 1)
          # Check if IMAGE_ID is not empty
          if [ -n "$IMAGE_ID" ]; then
            echo "Image ID: ${IMAGE_ID}"
            TAG="latest"
            docker tag $IMAGE_ID $REPO/$IMAGE_NAME:$TAG
            echo "Tagged image ID $IMAGE_ID with name $REPO/$IMAGE_NAME:$TAG
          else
            echo "No Docker images found."
          fi
          docker push $REPO/$IMAGE_NAME:$TAG

          # LATEST="${REPO}/${IMAGE_NAME}:latest"
          # docker tag ${IMAGE_ID} ${LATEST}
          # docker push ${LATEST}
          # echo "**Pushed:** ${IMAGE_NAME}:FULL_NAME" >> $GITHUB_STEP_SUMMARY

      - uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Container - Docker Hub
        run: |
          IMAGE_ID=$(docker images --filter "reference=politeauthority/polite-cicd" --format "{{.ID}}")
          REPO="docker.io"
          IMAGE_NAME="politeauthority/polite-cicd"
          TAG_NAME="$(task get-version)"
          FULL_NAME="${REPO}/${IMAGE_NAME}:${TAG_NAME}"
          docker tag ${IMAGE_ID} ${FULL_NAME}
          docker push ${FULL_NAME}

          LATEST="${REPO}/${IMAGE_NAME}:latest"
          docker tag ${IMAGE_ID} ${LATEST}
          docker push ${LATEST}
          echo "**Pushed:** ${IMAGE_NAME}:FULL_NAME" >> $GITHUB_STEP_SUMMARY

# End File: polite-cicd/.github/workflows/create-production.yaml
