# Create Production
# Builds and stores a new version of the image, reading the value of the `VERSION` file for the tag
# name

name: Create Production

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build-docker:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: harbor.squid-ink.us
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Container
        run: |
          echo "Run Task: Build"
          export CICD_TAG="${{ github.sha }}"
          task build

      - name: Push Container
        run: |
          IMAGE_ID=$(docker images --filter "reference=politeauthority/polite-cicd" --format "{{.ID}}")
          IMAGE_NAME="harbor.squid-ink.us/politeauthority/polite-cicd"
          TAG_NAME=$(task get-version)
          docker tag ${IMAGE_ID} ${IMAGE_NAME}:${TAG_NAME}
          docker push ${IMAGE_NAME}:${{ github.sha }}
          echo "## Docker Build" >> $GITHUB_STEP_SUMMARY
          echo "**Built:** ${IMAGE_NAME}:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY

# End File: polite-cicd/.github/workflows/pull-request.yaml
