# Pull Request

name: Pull-Request

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: ${{ vars.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: harbor.squid-ink.us
          username: ${{ vars.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Container
        run: |
          echo "Run Task: Build"
          export CICD_TAG="${{ github.sha }}"
          task build

      - name: Push Container
        run: |
          IMAGE_ID=$(docker images --filter "reference=politeauthority/polite-cicd" --format "{{.ID}}")
          REPO="harbor.squid-ink.us"
          IMAGE_NAME="politeauthority/polite-cicd"
          VERSION_NO=$(cat VERSION)
          TAG_NAME="${VERSION_NO}-${SHA:0:8}"
          FULL_NAME="${REPO}/${IMAGE_NAME}:${TAG_NAME}"
          docker tag ${IMAGE_ID} ${FULL_NAME}
          docker push ${FULL_NAME}
          echo "**Pushed:** ${FULL_NAME}" >> $GITHUB_STEP_SUMMARY

# End File: politeauthority/polite-cicd/.github/workflows/pull-request.yaml
